name: Linux

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:questing

    steps:
      - name: Install Checkout Dependencies
        run: apt update && apt install -y git

      - uses: actions/checkout@v5
        with:
          submodules: true

      # https://wiki.libsdl.org/SDL3/README-linux
      - name: Install Dependencies
        run: |
          apt update
          apt install -y build-essential make pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        run: cmake --build build --config $BUILD_TYPE

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: shiny
          path: ${{runner.workspace}}/build/libshiny.so
